<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;



class qualification_results22Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $qualificationResults=[];
        $qualificationResults[]=[
            "id"=>2201,
            "driver_id"=>16,
            'qualification_id'=>22,
            "q1"=>93.617,
            "q2"=>92.775,
            "q3"=>92.726,
            "position"=>1
        ];
        $qualificationResults[]=[
            "id"=>2202,
            "driver_id"=>55,
            'qualification_id'=>22,
            "q1"=>93.851,
            "q2"=>93.338,
            "q3"=>92.770,
            "position"=>2
        ];
        $qualificationResults[]=[
            "id"=>2203,
            "driver_id"=>1,
            'qualification_id'=>22,
            "q1"=>94.190,
            "q2"=>93.572,
            "q3"=>93.104,
            "position"=>3
        ];
        $qualificationResults[]=[
            "id"=>2204,
            "driver_id"=>63,
            'qualification_id'=>22,
            "q1"=>94.137,
            "q2"=>93.351,
            "q3"=>93.112,
            "position"=>4
        ];
        $qualificationResults[]=[
            "id"=>2205,
            "driver_id"=>10,
            'qualification_id'=>22,
            "q1"=>94.272,
            "q2"=>93.494,
            "q3"=>93.239,
            "position"=>5
        ];
        $qualificationResults[]=[
            "id"=>2206,
            "driver_id"=>23,
            'qualification_id'=>22,
            "q1"=>94.634,
            "q2"=>93.588,
            "q3"=>93.323,
            "position"=>6
        ];
        $qualificationResults[]=[
            "id"=>2207,
            "driver_id"=>2,
            'qualification_id'=>22,
            "q1"=>94.525,
            "q2"=>93.733,
            "q3"=>93.513,
            "position"=>7
        ];
        $qualificationResults[]=[
            "id"=>2208,
            "driver_id"=>77,
            'qualification_id'=>22,
            "q1"=>94.305,
            "q2"=>93.809,
            "q3"=>93.525,
            "position"=>8
        ];
        $qualificationResults[]=[
            "id"=>2209,
            "driver_id"=>20,
            'qualification_id'=>22,
            "q1"=>94.337,
            "q2"=>93.809,
            "q3"=>93.537,
            "position"=>9
        ];
        $qualificationResults[]=[
            "id"=>2210,
            "driver_id"=>14,
            'qualification_id'=>22,
            "q1"=>94.422,
            "q2"=>93.617,
            "q3"=>93.555,
            "position"=>10
        ];
        $qualificationResults[]=[
            "id"=>2211,
            "driver_id"=>44,
            'qualification_id'=>22,
            "q1"=>94.307,
            "q2"=>93.837,
            "q3"=>null,
            "position"=>11
        ];
        $qualificationResults[]=[
            "id"=>2212,
            "driver_id"=>11,
            'qualification_id'=>22,
            "q1"=>94.574,
            "q2"=>93.855,
            "q3"=>null,
            "position"=>12
        ];
        $qualificationResults[]=[
            "id"=>2213,
            "driver_id"=>27,
            'qualification_id'=>22,
            "q1"=>94.265,
            "q2"=>93.979,
            "q3"=>null,
            "position"=>13
        ];
        $qualificationResults[]=[
            "id"=>2214,
            "driver_id"=>18,
            'qualification_id'=>22,
            "q1"=>94.504,
            "q2"=>94.199,
            "q3"=>null,
            "position"=>14
        ];
        $qualificationResults[]=[
            "id"=>2215,
            "driver_id"=>3,
            'qualification_id'=>22,
            "q1"=>94.683,
            "q2"=>94.308,
            "q3"=>null,
            "position"=>15
        ];
        $qualificationResults[]=[
            "id"=>2216,
            "driver_id"=>4,
            'qualification_id'=>22,
            "q1"=>94.703,
            "q2"=>null,
            "q3"=>null,
            "position"=>16
        ];
        $qualificationResults[]=[
            "id"=>2217,
            "driver_id"=>31,
            'qualification_id'=>22,
            "q1"=>94.834,
            "q2"=>null,
            "q3"=>null,
            "position"=>17
        ];
        $qualificationResults[]=[
            "id"=>2218,
            "driver_id"=>24,
            'qualification_id'=>22,
            "q1"=>94.849,
            "q2"=>null,
            "q3"=>null,
            "position"=>18
        ];
        $qualificationResults[]=[
            "id"=>2219,
            "driver_id"=>81,
            'qualification_id'=>22,
            "q1"=>94.850,
            "q2"=>null,
            "q3"=>null,
            "position"=>19
        ];
        $qualificationResults[]=[
            "id"=>2220,
            "driver_id"=>22,
            'qualification_id'=>22,
            "q1"=>96.447,
            "q2"=>null,
            "q3"=>null,
            "position"=>20
        ];


        Db::table('qualification_results')->insert($qualificationResults);
    }
}
