<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;



class qualification_results15Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $qualificationResults=[];
        $qualificationResults[]=[
            "id"=>1501,
            "driver_id"=>55,
            'qualification_id'=>15,
            "q1"=>81.965,
            "q2"=>80.991,
            "q3"=>80.294,
            "position"=>1
        ];
        $qualificationResults[]=[
            "id"=>1502,
            "driver_id"=>1,
            'qualification_id'=>15,
            "q1"=>81.573,
            "q2"=>80.937,
            "q3"=>80.307,
            "position"=>2
        ];
        $qualificationResults[]=[
            "id"=>1503,
            "driver_id"=>16,
            'qualification_id'=>15,
            "q1"=>81.788,
            "q2"=>80.977,
            "q3"=>80.361,
            "position"=>3
        ];
        $qualificationResults[]=[
            "id"=>1504,
            "driver_id"=>63,
            'qualification_id'=>15,
            "q1"=>82.148,
            "q2"=>81.382,
            "q3"=>80.671,
            "position"=>4
        ];
        $qualificationResults[]=[
            "id"=>1505,
            "driver_id"=>11,
            'qualification_id'=>15,
            "q1"=>81.911,
            "q2"=>81.240,
            "q3"=>80.688,
            "position"=>5
        ];
        $qualificationResults[]=[
            "id"=>1506,
            "driver_id"=>23,
            'qualification_id'=>15,
            "q1"=>81.661,
            "q2"=>81.272,
            "q3"=>80.760,
            "position"=>6
        ];
        $qualificationResults[]=[
            "id"=>1507,
            "driver_id"=>81,
            'qualification_id'=>15,
            "q1"=>82.106,
            "q2"=>81.527,
            "q3"=>80.785,
            "position"=>7
        ];
        $qualificationResults[]=[
            "id"=>1508,
            "driver_id"=>44,
            'qualification_id'=>15,
            "q1"=>81.977,
            "q2"=>81.369,
            "q3"=>80.820,
            "position"=>8
        ];
        $qualificationResults[]=[
            "id"=>1509,
            "driver_id"=>14,
            'qualification_id'=>15,
            "q1"=>81.995,
            "q2"=>81.581,
            "q3"=>80.979,
            "position"=>9
        ];
        $qualificationResults[]=[
            "id"=>1510,
            "driver_id"=>4,
            'qualification_id'=>15,
            "q1"=>82.043,
            "q2"=>81.543,
            "q3"=>81.417,
            "position"=>10
        ];
        $qualificationResults[]=[
            "id"=>1511,
            "driver_id"=>22,
            'qualification_id'=>15,
            "q1"=>81.852,
            "q2"=>81.594,
            "q3"=>null,
            "position"=>11
        ];
        $qualificationResults[]=[
            "id"=>1512,
            "driver_id"=>40,
            'qualification_id'=>15,
            "q1"=>82.112,
            "q2"=>81.758,
            "q3"=>null,
            "position"=>12
        ];
        $qualificationResults[]=[
            "id"=>1513,
            "driver_id"=>27,
            'qualification_id'=>15,
            "q1"=>82.343,
            "q2"=>81.776,
            "q3"=>null,
            "position"=>13
        ];
        $qualificationResults[]=[
            "id"=>1514,
            "driver_id"=>77,
            'qualification_id'=>15,
            "q1"=>82.249,
            "q2"=>81.940,
            "q3"=>null,
            "position"=>14
        ];
        $qualificationResults[]=[
            "id"=>1515,
            "driver_id"=>2,
            'qualification_id'=>15,
            "q1"=>81.930,
            "q2"=>81.944,
            "q3"=>null,
            "position"=>15
        ];
        $qualificationResults[]=[
            "id"=>1516,
            "driver_id"=>24,
            'qualification_id'=>15,
            "q1"=>82.390,
            "q2"=>null,
            "q3"=>null,
            "position"=>16
        ];
        $qualificationResults[]=[
            "id"=>1517,
            "driver_id"=>10,
            'qualification_id'=>15,
            "q1"=>82.545,
            "q2"=>null,
            "q3"=>null,
            "position"=>17
        ];
        $qualificationResults[]=[
            "id"=>1518,
            "driver_id"=>31,
            'qualification_id'=>15,
            "q1"=>82.548,
            "q2"=>null,
            "q3"=>null,
            "position"=>18
        ];
        $qualificationResults[]=[
            "id"=>1519,
            "driver_id"=>20,
            'qualification_id'=>15,
            "q1"=>82.592,
            "q2"=>null,
            "q3"=>null,
            "position"=>19
        ];
        $qualificationResults[]=[
            "id"=>1520,
            "driver_id"=>18,
            'qualification_id'=>15,
            "q1"=>82.860,
            "q2"=>null,
            "q3"=>null,
            "position"=>20
        ];


        Db::table('qualification_results')->insert($qualificationResults);
    }
}
