<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;



class qualification_results13Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $qualificationResults=[];
        $qualificationResults[]=[
            "id"=>1301,
            "driver_id"=>44,
            'qualification_id'=>13,
            "q1"=>78.577,
            "q2"=>77.427,
            "q3"=>76.608,
            "position"=>1
        ];
        $qualificationResults[]=[
            "id"=>1302,
            "driver_id"=>1,
            'qualification_id'=>13,
            "q1"=>78.318,
            "q2"=>77.547,
            "q3"=>76.612,
            "position"=>2
        ];
        $qualificationResults[]=[
            "id"=>1303,
            "driver_id"=>4,
            'qualification_id'=>13,
            "q1"=>78.697,
            "q2"=>77.328,
            "q3"=>76.694,
            "position"=>3
        ];
        $qualificationResults[]=[
            "id"=>1304,
            "driver_id"=>81,
            'qualification_id'=>13,
            "q1"=>78.464,
            "q2"=>77.571,
            "q3"=>76.905,
            "position"=>4
        ];
        $qualificationResults[]=[
            "id"=>1305,
            "driver_id"=>24,
            'qualification_id'=>13,
            "q1"=>78.143,
            "q2"=>77.700,
            "q3"=>76.971,
            "position"=>5
        ];
        $qualificationResults[]=[
            "id"=>1306,
            "driver_id"=>16,
            'qualification_id'=>13,
            "q1"=>78.440,
            "q2"=>77.580,
            "q3"=>76.992,
            "position"=>6
        ];
        $qualificationResults[]=[
            "id"=>1307,
            "driver_id"=>77,
            'qualification_id'=>13,
            "q1"=>78.775,
            "q2"=>77.563,
            "q3"=>77.034,
            "position"=>7
        ];
        $qualificationResults[]=[
            "id"=>1308,
            "driver_id"=>14,
            'qualification_id'=>13,
            "q1"=>78.580,
            "q2"=>77.701,
            "q3"=>77.035,
            "position"=>8
        ];
        $qualificationResults[]=[
            "id"=>1309,
            "driver_id"=>11,
            'qualification_id'=>13,
            "q1"=>78.360,
            "q2"=>77.675,
            "q3"=>77.045,
            "position"=>9
        ];
        $qualificationResults[]=[
            "id"=>1310,
            "driver_id"=>27,
            'qualification_id'=>13,
            "q1"=>78.695,
            "q2"=>77.652,
            "q3"=>77.186,
            "position"=>10
        ];
        $qualificationResults[]=[
            "id"=>1311,
            "driver_id"=>22,
            'qualification_id'=>13,
            "q1"=>119.044,
            "q2"=>113.148,
            "q3"=>null,
            "position"=>11
        ];
        $qualificationResults[]=[
            "id"=>1312,
            "driver_id"=>10,
            'qualification_id'=>13,
            "q1"=>119.511,
            "q2"=>113.671,
            "q3"=>null,
            "position"=>12
        ];
        $qualificationResults[]=[
            "id"=>1313,
            "driver_id"=>20,
            'qualification_id'=>13,
            "q1"=>120.020,
            "q2"=>114.160,
            "q3"=>null,
            "position"=>13
        ];
        $qualificationResults[]=[
            "id"=>1314,
            "driver_id"=>77,
            'qualification_id'=>13,
            "q1"=>119.484,
            "q2"=>114.694,
            "q3"=>null,
            "position"=>14
        ];
        $qualificationResults[]=[
            "id"=>1315,
            "driver_id"=>31,
            'qualification_id'=>13,
            "q1"=>119.511,
            "q2"=>116.372,
            "q3"=>null,
            "position"=>15
        ];
        $qualificationResults[]=[
            "id"=>1316,
            "driver_id"=>23,
            'qualification_id'=>13,
            "q1"=>120.314,
            "q2"=>null,
            "q3"=>null,
            "position"=>16
        ];
        $qualificationResults[]=[
            "id"=>1317,
            "driver_id"=>24,
            'qualification_id'=>13,
            "q1"=>120.832,
            "q2"=>null,
            "q3"=>null,
            "position"=>17
        ];
        $qualificationResults[]=[
            "id"=>1318,
            "driver_id"=>2,
            'qualification_id'=>13,
            "q1"=>121.535,
            "q2"=>null,
            "q3"=>null,
            "position"=>18
        ];
        $qualificationResults[]=[
            "id"=>1319,
            "driver_id"=>3,
            'qualification_id'=>13,
            "q1"=>122.159,
            "q2"=>null,
            "q3"=>null,
            "position"=>19
        ];
        $qualificationResults[]=[
            "id"=>1320,
            "driver_id"=>27,
            'qualification_id'=>13,
            "q1"=>123.166,
            "q2"=>null,
            "q3"=>null,
            "position"=>20
        ];


        Db::table('qualification_results')->insert($qualificationResults);
    }
}
