<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;



class qualification_results11Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $qualificationResults=[];
        $qualificationResults[]=[
            "id"=>1101,
            "driver_id"=>1,
            'qualification_id'=>11,
            "q1"=>65.116,
            "q2"=>64.951,
            "q3"=>86.720,
            "position"=>1
        ];
        $qualificationResults[]=[
            "id"=>1102,
            "driver_id"=>4,
            'qualification_id'=>11,
            "q1"=>65.577,
            "q2"=>65.087,
            "q3"=>86.961,
            "position"=>2
        ];
        $qualificationResults[]=[
            "id"=>1103,
            "driver_id"=>81,
            'qualification_id'=>11,
            "q1"=>65.339,
            "q2"=>64.975,
            "q3"=>87.092,
            "position"=>3
        ];
        $qualificationResults[]=[
            "id"=>1104,
            "driver_id"=>16,
            'qualification_id'=>11,
            "q1"=>65.617,
            "q2"=>65.038,
            "q3"=>87.136,
            "position"=>4
        ];
        $qualificationResults[]=[
            "id"=>1105,
            "driver_id"=>55,
            'qualification_id'=>11,
            "q1"=>65.673,
            "q2"=>65.188,
            "q3"=>87.148,
            "position"=>5
        ];
        $qualificationResults[]=[
            "id"=>1106,
            "driver_id"=>63,
            'qualification_id'=>11,
            "q1"=>65.710,
            "q2"=>65.121,
            "q3"=>87.155,
            "position"=>6
        ];
        $qualificationResults[]=[
            "id"=>1107,
            "driver_id"=>44,
            'qualification_id'=>11,
            "q1"=>65.655,
            "q2"=>65.181,
            "q3"=>87.211,
            "position"=>7
        ];
        $qualificationResults[]=[
            "id"=>1108,
            "driver_id"=>23,
            'qualification_id'=>11,
            "q1"=>65.740,
            "q2"=>65.301,
            "q3"=>87.530,
            "position"=>8
        ];
        $qualificationResults[]=[
            "id"=>1109,
            "driver_id"=>14,
            'qualification_id'=>11,
            "q1"=>65.515,
            "q2"=>65.084,
            "q3"=>87.659,
            "position"=>9
        ];
        $qualificationResults[]=[
            "id"=>1110,
            "driver_id"=>10,
            'qualification_id'=>11,
            "q1"=>65.673,
            "q2"=>65.387,
            "q3"=>87.689,
            "position"=>10
        ];
        $qualificationResults[]=[
            "id"=>1111,
            "driver_id"=>27,
            'qualification_id'=>11,
            "q1"=>89.603,
            "q2"=>88.896,
            "q3"=>null,
            "position"=>11
        ];
        $qualificationResults[]=[
            "id"=>1112,
            "driver_id"=>18,
            'qualification_id'=>11,
            "q1"=>89.448,
            "q2"=>88.935,
            "q3"=>null,
            "position"=>12
        ];
        $qualificationResults[]=[
            "id"=>1113,
            "driver_id"=>31,
            'qualification_id'=>11,
            "q1"=>89.700,
            "q2"=>88.956,
            "q3"=>null,
            "position"=>13
        ];
        $qualificationResults[]=[
            "id"=>1114,
            "driver_id"=>2,
            'qualification_id'=>11,
            "q1"=>89.873,
            "q2"=>89.031,
            "q3"=>null,
            "position"=>14
        ];
        $qualificationResults[]=[
            "id"=>1115,
            "driver_id"=>77,
            'qualification_id'=>11,
            "q1"=>89.798,
            "q2"=>null,
            "q3"=>null,
            "position"=>15
        ];
        $qualificationResults[]=[
            "id"=>1116,
            "driver_id"=>11,
            'qualification_id'=>11,
            "q1"=>89.968,
            "q2"=>null,
            "q3"=>null,
            "position"=>16
        ];
        $qualificationResults[]=[
            "id"=>1117,
            "driver_id"=>22,
            'qualification_id'=>11,
            "q1"=>90.025,
            "q2"=>null,
            "q3"=>null,
            "position"=>17
        ];
        $qualificationResults[]=[
            "id"=>1118,
            "driver_id"=>24,
            'qualification_id'=>11,
            "q1"=>90.123,
            "q2"=>null,
            "q3"=>null,
            "position"=>18
        ];
        $qualificationResults[]=[
            "id"=>1119,
            "driver_id"=>21,
            'qualification_id'=>11,
            "q1"=>90.513,
            "q2"=>null,
            "q3"=>null,
            "position"=>19
        ];
        $qualificationResults[]=[
            "id"=>1120,
            "driver_id"=>20,
            'qualification_id'=>11,
            "q1"=>92.513,
            "q2"=>null,
            "q3"=>null,
            "position"=>20
        ];


        Db::table('qualification_results')->insert($qualificationResults);
    }
}
