<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;



class qualification_results12Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $qualificationResults=[];
        $qualificationResults[]=[
            "id"=>1201,
            "driver_id"=>44,
            'qualification_id'=>12,
            "q1"=>78.577,
            "q2"=>77.427,
            "q3"=>76.608,
            "position"=>1
        ];
        $qualificationResults[]=[
            "id"=>1202,
            "driver_id"=>1,
            'qualification_id'=>12,
            "q1"=>78.318,
            "q2"=>77.547,
            "q3"=>76.612,
            "position"=>2
        ];
        $qualificationResults[]=[
            "id"=>1203,
            "driver_id"=>4,
            'qualification_id'=>12,
            "q1"=>78.697,
            "q2"=>77.328,
            "q3"=>76.694,
            "position"=>3
        ];
        $qualificationResults[]=[
            "id"=>1204,
            "driver_id"=>81,
            'qualification_id'=>12,
            "q1"=>78.464,
            "q2"=>77.571,
            "q3"=>76.905,
            "position"=>4
        ];
        $qualificationResults[]=[
            "id"=>1205,
            "driver_id"=>24,
            'qualification_id'=>12,
            "q1"=>78.143,
            "q2"=>77.700,
            "q3"=>76.971,
            "position"=>5
        ];
        $qualificationResults[]=[
            "id"=>1206,
            "driver_id"=>16,
            'qualification_id'=>12,
            "q1"=>78.440,
            "q2"=>77.580,
            "q3"=>76.992,
            "position"=>6
        ];
        $qualificationResults[]=[
            "id"=>1207,
            "driver_id"=>77,
            'qualification_id'=>12,
            "q1"=>78.775,
            "q2"=>77.563,
            "q3"=>77.034,
            "position"=>7
        ];
        $qualificationResults[]=[
            "id"=>1208,
            "driver_id"=>14,
            'qualification_id'=>12,
            "q1"=>78.580,
            "q2"=>77.701,
            "q3"=>77.035,
            "position"=>8
        ];
        $qualificationResults[]=[
            "id"=>1209,
            "driver_id"=>11,
            'qualification_id'=>12,
            "q1"=>78.360,
            "q2"=>77.675,
            "q3"=>77.045,
            "position"=>9
        ];
        $qualificationResults[]=[
            "id"=>1210,
            "driver_id"=>27,
            'qualification_id'=>12,
            "q1"=>78.695,
            "q2"=>77.652,
            "q3"=>77.186,
            "position"=>10
        ];
        $qualificationResults[]=[
            "id"=>1211,
            "driver_id"=>55,
            'qualification_id'=>12,
            "q1"=>79.168,
            "q2"=>77.703,
            "q3"=>null,
            "position"=>11
        ];
        $qualificationResults[]=[
            "id"=>1212,
            "driver_id"=>31,
            'qualification_id'=>12,
            "q1"=>78.854,
            "q2"=>77.841,
            "q3"=>null,
            "position"=>12
        ];
        $qualificationResults[]=[
            "id"=>1213,
            "driver_id"=>3,
            'qualification_id'=>12,
            "q1"=>79.037,
            "q2"=>78.002,
            "q3"=>null,
            "position"=>13
        ];
        $qualificationResults[]=[
            "id"=>1214,
            "driver_id"=>18,
            'qualification_id'=>12,
            "q1"=>79.457,
            "q2"=>78.144,
            "q3"=>null,
            "position"=>14
        ];
        $qualificationResults[]=[
            "id"=>1215,
            "driver_id"=>10,
            'qualification_id'=>12,
            "q1"=>89.798,
            "q2"=>78.217,
            "q3"=>null,
            "position"=>15
        ];
        $qualificationResults[]=[
            "id"=>1216,
            "driver_id"=>23,
            'qualification_id'=>12,
            "q1"=>78.917,
            "q2"=>null,
            "q3"=>null,
            "position"=>16
        ];
        $qualificationResults[]=[
            "id"=>1217,
            "driver_id"=>22,
            'qualification_id'=>12,
            "q1"=>78.919,
            "q2"=>null,
            "q3"=>null,
            "position"=>17
        ];
        $qualificationResults[]=[
            "id"=>1218,
            "driver_id"=>63,
            'qualification_id'=>12,
            "q1"=>79.027,
            "q2"=>null,
            "q3"=>null,
            "position"=>18
        ];
        $qualificationResults[]=[
            "id"=>1219,
            "driver_id"=>20,
            'qualification_id'=>12,
            "q1"=>79.206,
            "q2"=>null,
            "q3"=>null,
            "position"=>19
        ];
        $qualificationResults[]=[
            "id"=>1220,
            "driver_id"=>2,
            'qualification_id'=>12,
            "q1"=>79.248,
            "q2"=>null,
            "q3"=>null,
            "position"=>20
        ];


        Db::table('qualification_results')->insert($qualificationResults);
    }
}
