<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;



class qualification_results04Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $qualificationResults=[];
        $qualificationResults[]=[
            "id"=>401,
            "driver_id"=>16,
            'qualification_id'=>4,
            "q1"=>101.269,
            "q2"=>101.037,
            "q3"=>100.203,
            "position"=>1
        ];
        $qualificationResults[]=[
            "id"=>402,
            "driver_id"=>1,
            'qualification_id'=>4,
            "q1"=>101.398,
            "q2"=>100.822,
            "q3"=>100.391,
            "position"=>2
        ];
        $qualificationResults[]=[
            "id"=>403,
            "driver_id"=>11,
            'qualification_id'=>4,
            "q1"=>101.756,
            "q2"=>101.131,
            "q3"=>100.495,
            "position"=>3
        ];
        $qualificationResults[]=[
            "id"=>404,
            "driver_id"=>55,
            'qualification_id'=>4,
            "q1"=>102.197,
            "q2"=>101.369,
            "q3"=>101.016,
            "position"=>4
        ];
        $qualificationResults[]=[
            "id"=>405,
            "driver_id"=>44,
            'qualification_id'=>4,
            "q1"=>102.113,
            "q2"=>101.650,
            "q3"=>101.177,
            "position"=>5
        ];
        $qualificationResults[]=[
            "id"=>406,
            "driver_id"=>14,
            'qualification_id'=>4,
            "q1"=>101.720,
            "q2"=>101.370,
            "q3"=>101.253,
            "position"=>6
        ];
        $qualificationResults[]=[
            "id"=>407,
            "driver_id"=>4,
            'qualification_id'=>4,
            "q1"=>102.154,
            "q2"=>101.485,
            "q3"=>101.281,
            "position"=>7
        ];
        $qualificationResults[]=[
            "id"=>408,
            "driver_id"=>22,
            'qualification_id'=>4,
            "q1"=>102.234,
            "q2"=>101.569,
            "q3"=>101.581,
            "position"=>8
        ];
        $qualificationResults[]=[
            "id"=>409,
            "driver_id"=>18,
            'qualification_id'=>4,
            "q1"=>102.524,
            "q2"=>101.576,
            "q3"=>101.611,
            "position"=>9
        ];
        $qualificationResults[]=[
            "id"=>410,
            "driver_id"=>81,
            'qualification_id'=>4,
            "q1"=>102.455,
            "q2"=>101.636,
            "q3"=>101.611,
            "position"=>10
        ];
        $qualificationResults[]=[
            "id"=>411,
            "driver_id"=>63,
            'qualification_id'=>4,
            "q1"=>102.073,
            "q2"=>101.654,
            "q3"=>null,
            "position"=>11
        ];
        $qualificationResults[]=[
            "id"=>412,
            "driver_id"=>31,
            'qualification_id'=>4,
            "q1"=>102.622,
            "q2"=>101.798,
            "q3"=>null,
            "position"=>12
        ];
        $qualificationResults[]=[
            "id"=>413,
            "driver_id"=>23,
            'qualification_id'=>4,
            "q1"=>102.171,
            "q2"=>101.818,
            "q3"=>null,
            "position"=>13
        ];
        $qualificationResults[]=[
            "id"=>414,
            "driver_id"=>77,
            'qualification_id'=>4,
            "q1"=>102.582,
            "q2"=>102.259,
            "q3"=>null,
            "position"=>14
        ];
        $qualificationResults[]=[
            "id"=>415,
            "driver_id"=>2,
            'qualification_id'=>4,
            "q1"=>102.242,
            "q2"=>102.395,
            "q3"=>null,
            "position"=>15
        ];
        $qualificationResults[]=[
            "id"=>416,
            "driver_id"=>24,
            'qualification_id'=>4,
            "q1"=>102.642,
            "q2"=>null,
            "q3"=>null,
            "position"=>16
        ];
        $qualificationResults[]=[
            "id"=>417,
            "driver_id"=>27,
            'qualification_id'=>4,
            "q1"=>102.755,
            "q2"=>null,
            "q3"=>null,
            "position"=>17
        ];
        $qualificationResults[]=[
            "id"=>418,
            "driver_id"=>20,
            'qualification_id'=>4,
            "q1"=>103.417,
            "q2"=>null,
            "q3"=>null,
            "position"=>18
        ];
        $qualificationResults[]=[
            "id"=>419,
            "driver_id"=>10,
            'qualification_id'=>4,
            "q1"=>104.853,
            "q2"=>null,
            "q3"=>null,
            "position"=>19
        ];
        $qualificationResults[]=[
            "id"=>420,
            "driver_id"=>11,
            'qualification_id'=>4,
            "q1"=>115.282,
            "q2"=>null,
            "q3"=>null,
            "position"=>20
        ];


        Db::table('qualification_results')->insert($qualificationResults);
    }
}
