<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;



class qualification_results18Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $qualificationResults=[];
        $qualificationResults[]=[
            "id"=>1801,
            "driver_id"=>1,
            'qualification_id'=>18,
            "q1"=>85.007,
            "q2"=>84.483,
            "q3"=>83.778,
            "position"=>1
        ];
        $qualificationResults[]=[
            "id"=>1802,
            "driver_id"=>63,
            'qualification_id'=>18,
            "q1"=>85.334,
            "q2"=>84.0827,
            "q3"=>84.219,
            "position"=>2
        ];
        $qualificationResults[]=[
            "id"=>1803,
            "driver_id"=>44,
            'qualification_id'=>18,
            "q1"=>86.076,
            "q2"=>84.381,
            "q3"=>84.305,
            "position"=>3
        ];
        $qualificationResults[]=[
            "id"=>1804,
            "driver_id"=>14,
            'qualification_id'=>18,
            "q1"=>85.223,
            "q2"=>85.241,
            "q3"=>84.305,
            "position"=>4
        ];
        $qualificationResults[]=[
            "id"=>1805,
            "driver_id"=>16,
            'qualification_id'=>18,
            "q1"=>85.452,
            "q2"=>85.079,
            "q3"=>84.424,
            "position"=>5
        ];
        $qualificationResults[]=[
            "id"=>1806,
            "driver_id"=>81,
            'qualification_id'=>18,
            "q1"=>85.266,
            "q2"=>84.724,
            "q3"=>84.540,
            "position"=>6
        ];
        $qualificationResults[]=[
            "id"=>1807,
            "driver_id"=>10,
            'qualification_id'=>18,
            "q1"=>85.566,
            "q2"=>84.918,
            "q3"=>84.553,
            "position"=>7
        ];
        $qualificationResults[]=[
            "id"=>1808,
            "driver_id"=>31,
            'qualification_id'=>18,
            "q1"=>85.711,
            "q2"=>84.918,
            "q3"=>84.763,
            "position"=>8
        ];
        $qualificationResults[]=[
            "id"=>1809,
            "driver_id"=>77,
            'qualification_id'=>18,
            "q1"=>86.038,
            "q2"=>85.297,
            "q3"=>85.058,
            "position"=>9
        ];
        $qualificationResults[]=[
            "id"=>1810,
            "driver_id"=>4,
            'qualification_id'=>18,
            "q1"=>85.131,
            "q2"=>84.685,
            "q3"=>null,
            "position"=>10
        ];
        $qualificationResults[]=[
            "id"=>1811,
            "driver_id"=>22,
            'qualification_id'=>18,
            "q1"=>86.058,
            "q2"=>85.301,
            "q3"=>null,
            "position"=>11
        ];
        $qualificationResults[]=[
            "id"=>1812,
            "driver_id"=>55,
            'qualification_id'=>18,
            "q1"=>85.808,
            "q2"=>85.301,
            "q3"=>null,
            "position"=>12
        ];
        $qualificationResults[]=[
            "id"=>1813,
            "driver_id"=>11,
            'qualification_id'=>18,
            "q1"=>85.991,
            "q2"=>85.462,
            "q3"=>null,
            "position"=>13
        ];
        $qualificationResults[]=[
            "id"=>1814,
            "driver_id"=>23,
            'qualification_id'=>18,
            "q1"=>86.118,
            "q2"=>85.707,
            "q3"=>null,
            "position"=>14
        ];
        $qualificationResults[]=[
            "id"=>1815,
            "driver_id"=>27,
            'qualification_id'=>18,
            "q1"=>85.904,
            "q2"=>85.783,
            "q3"=>null,
            "position"=>15
        ];
        $qualificationResults[]=[
            "id"=>1816,
            "driver_id"=>2,
            'qualification_id'=>18,
            "q1"=>86.345,
            "q2"=>null,
            "q3"=>null,
            "position"=>16
        ];
        $qualificationResults[]=[
            "id"=>1817,
            "driver_id"=>18,
            'qualification_id'=>18,
            "q1"=>86.345,
            "q2"=>null,
            "q3"=>null,
            "position"=>17
        ];
        $qualificationResults[]=[
            "id"=>1818,
            "driver_id"=>40,
            'qualification_id'=>18,
            "q1"=>86.635,
            "q2"=>null,
            "q3"=>null,
            "position"=>18
        ];
        $qualificationResults[]=[
            "id"=>1819,
            "driver_id"=>20,
            'qualification_id'=>18,
            "q1"=>87.046,
            "q2"=>null,
            "q3"=>null,
            "position"=>19
        ];
        $qualificationResults[]=[
            "id"=>1820,
            "driver_id"=>24,
            'qualification_id'=>18,
            "q1"=>87.432,
            "q2"=>null,
            "q3"=>null,
            "position"=>20
        ];


        Db::table('qualification_results')->insert($qualificationResults);
    }
}
