<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;



class qualification_results13Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $qualificationResults=[];
        $qualificationResults[]=[
            "id"=>1301,
            "driver_id"=>1,
            'qualification_id'=>13,
            "q1"=>118.515,
            "q2"=>112.784,
            "q3"=>106.168,
            "position"=>1
        ];
        $qualificationResults[]=[
            "id"=>1302,
            "driver_id"=>16,
            'qualification_id'=>13,
            "q1"=>118.300,
            "q2"=>112.017,
            "q3"=>106.988,
            "position"=>2
        ];
        $qualificationResults[]=[
            "id"=>1303,
            "driver_id"=>11,
            'qualification_id'=>13,
            "q1"=>118.899,
            "q2"=>112.017,
            "q3"=>107.045,
            "position"=>3
        ];
        $qualificationResults[]=[
            "id"=>1304,
            "driver_id"=>44,
            'qualification_id'=>13,
            "q1"=>118.563,
            "q2"=>112.345,
            "q3"=>107.087,
            "position"=>4
        ];
        $qualificationResults[]=[
            "id"=>1305,
            "driver_id"=>55,
            'qualification_id'=>13,
            "q1"=>118.688,
            "q2"=>111.711,
            "q3"=>107.152,
            "position"=>5
        ];
        $qualificationResults[]=[
            "id"=>1306,
            "driver_id"=>81,
            'qualification_id'=>13,
            "q1"=>118.872,
            "q2"=>111.534,
            "q3"=>107.365,
            "position"=>6
        ];
        $qualificationResults[]=[
            "id"=>1307,
            "driver_id"=>4,
            'qualification_id'=>13,
            "q1"=>119.981,
            "q2"=>112.252,
            "q3"=>107.669,
            "position"=>7
        ];
        $qualificationResults[]=[
            "id"=>1308,
            "driver_id"=>63,
            'qualification_id'=>13,
            "q1"=>119.035,
            "q2"=>112.605,
            "q3"=>107.805,
            "position"=>8
        ];
        $qualificationResults[]=[
            "id"=>1309,
            "driver_id"=>14,
            'qualification_id'=>13,
            "q1"=>118.834,
            "q2"=>112.751,
            "q3"=>107.843,
            "position"=>9
        ];
        $qualificationResults[]=[
            "id"=>1310,
            "driver_id"=>18,
            'qualification_id'=>13,
            "q1"=>119.663,
            "q2"=>112.193,
            "q3"=>108.841,
            "position"=>10
        ];
        $qualificationResults[]=[
            "id"=>1311,
            "driver_id"=>22,
            'qualification_id'=>13,
            "q1"=>119.044,
            "q2"=>113.148,
            "q3"=>null,
            "position"=>11
        ];
        $qualificationResults[]=[
            "id"=>1312,
            "driver_id"=>10,
            'qualification_id'=>13,
            "q1"=>119.511,
            "q2"=>113.671,
            "q3"=>null,
            "position"=>12
        ];
        $qualificationResults[]=[
            "id"=>1313,
            "driver_id"=>20,
            'qualification_id'=>13,
            "q1"=>120.020,
            "q2"=>114.160,
            "q3"=>null,
            "position"=>13
        ];
        $qualificationResults[]=[
            "id"=>1314,
            "driver_id"=>77,
            'qualification_id'=>13,
            "q1"=>119.484,
            "q2"=>114.694,
            "q3"=>null,
            "position"=>14
        ];
        $qualificationResults[]=[
            "id"=>1315,
            "driver_id"=>31,
            'qualification_id'=>13,
            "q1"=>119.511,
            "q2"=>116.372,
            "q3"=>null,
            "position"=>15
        ];
        $qualificationResults[]=[
            "id"=>1316,
            "driver_id"=>23,
            'qualification_id'=>13,
            "q1"=>120.314,
            "q2"=>null,
            "q3"=>null,
            "position"=>16
        ];
        $qualificationResults[]=[
            "id"=>1317,
            "driver_id"=>24,
            'qualification_id'=>13,
            "q1"=>120.832,
            "q2"=>null,
            "q3"=>null,
            "position"=>17
        ];
        $qualificationResults[]=[
            "id"=>1318,
            "driver_id"=>2,
            'qualification_id'=>13,
            "q1"=>121.535,
            "q2"=>null,
            "q3"=>null,
            "position"=>18
        ];
        $qualificationResults[]=[
            "id"=>1319,
            "driver_id"=>3,
            'qualification_id'=>13,
            "q1"=>122.159,
            "q2"=>null,
            "q3"=>null,
            "position"=>19
        ];
        $qualificationResults[]=[
            "id"=>1320,
            "driver_id"=>27,
            'qualification_id'=>13,
            "q1"=>123.166,
            "q2"=>null,
            "q3"=>null,
            "position"=>20
        ];


        Db::table('qualification_results')->insert($qualificationResults);
    }
}
