<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;



class qualification_results14Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $qualificationResults=[];
        $qualificationResults[]=[
            "id"=>1401,
            "driver_id"=>1,
            'qualification_id'=>14,
            "q1"=>118.515,
            "q2"=>112.784,
            "q3"=>106.168,
            "position"=>1
        ];
        $qualificationResults[]=[
            "id"=>1402,
            "driver_id"=>16,
            'qualification_id'=>14,
            "q1"=>118.300,
            "q2"=>112.017,
            "q3"=>106.988,
            "position"=>2
        ];
        $qualificationResults[]=[
            "id"=>1403,
            "driver_id"=>11,
            'qualification_id'=>14,
            "q1"=>118.899,
            "q2"=>112.017,
            "q3"=>107.045,
            "position"=>3
        ];
        $qualificationResults[]=[
            "id"=>1404,
            "driver_id"=>44,
            'qualification_id'=>14,
            "q1"=>118.563,
            "q2"=>112.345,
            "q3"=>107.087,
            "position"=>4
        ];
        $qualificationResults[]=[
            "id"=>1405,
            "driver_id"=>55,
            'qualification_id'=>14,
            "q1"=>118.688,
            "q2"=>111.711,
            "q3"=>107.152,
            "position"=>5
        ];
        $qualificationResults[]=[
            "id"=>1406,
            "driver_id"=>81,
            'qualification_id'=>14,
            "q1"=>118.872,
            "q2"=>111.534,
            "q3"=>107.365,
            "position"=>6
        ];
        $qualificationResults[]=[
            "id"=>1407,
            "driver_id"=>4,
            'qualification_id'=>14,
            "q1"=>119.981,
            "q2"=>112.252,
            "q3"=>107.669,
            "position"=>7
        ];
        $qualificationResults[]=[
            "id"=>1408,
            "driver_id"=>63,
            'qualification_id'=>14,
            "q1"=>119.035,
            "q2"=>112.605,
            "q3"=>107.805,
            "position"=>8
        ];
        $qualificationResults[]=[
            "id"=>1409,
            "driver_id"=>14,
            'qualification_id'=>14,
            "q1"=>118.834,
            "q2"=>112.751,
            "q3"=>107.843,
            "position"=>9
        ];
        $qualificationResults[]=[
            "id"=>1410,
            "driver_id"=>18,
            'qualification_id'=>14,
            "q1"=>119.663,
            "q2"=>112.193,
            "q3"=>108.841,
            "position"=>10
        ];
        $qualificationResults[]=[
            "id"=>1411,
            "driver_id"=>18,
            'qualification_id'=>14,
            "q1"=>81.570,
            "q2"=>80.121,
            "q3"=>null,
            "position"=>11
        ];
        $qualificationResults[]=[
            "id"=>1412,
            "driver_id"=>10,
            'qualification_id'=>14,
            "q1"=>81.735,
            "q2"=>80.128,
            "q3"=>null,
            "position"=>12
        ];
        $qualificationResults[]=[
            "id"=>1413,
            "driver_id"=>44,
            'qualification_id'=>14,
            "q1"=>81.919,
            "q2"=>80.151,
            "q3"=>null,
            "position"=>13
        ];
        $qualificationResults[]=[
            "id"=>1414,
            "driver_id"=>22,
            'qualification_id'=>14,
            "q1"=>81.781,
            "q2"=>80.230,
            "q3"=>null,
            "position"=>14
        ];
        $qualificationResults[]=[
            "id"=>1415,
            "driver_id"=>27,
            'qualification_id'=>14,
            "q1"=>81.891,
            "q2"=>80.250,
            "q3"=>null,
            "position"=>15
        ];
        $qualificationResults[]=[
            "id"=>1416,
            "driver_id"=>24,
            'qualification_id'=>14,
            "q1"=>82.067,
            "q2"=>null,
            "q3"=>null,
            "position"=>16
        ];
        $qualificationResults[]=[
            "id"=>1417,
            "driver_id"=>31,
            'qualification_id'=>14,
            "q1"=>82.110,
            "q2"=>null,
            "q3"=>null,
            "position"=>17
        ];
        $qualificationResults[]=[
            "id"=>1418,
            "driver_id"=>20,
            'qualification_id'=>14,
            "q1"=>82.192,
            "q2"=>null,
            "q3"=>null,
            "position"=>18
        ];
        $qualificationResults[]=[
            "id"=>1419,
            "driver_id"=>77,
            'qualification_id'=>14,
            "q1"=>82.260,
            "q2"=>null,
            "q3"=>null,
            "position"=>19
        ];
        $qualificationResults[]=[
            "id"=>1420,
            "driver_id"=>40,
            'qualification_id'=>14,
            "q1"=>83.420,
            "q2"=>null,
            "q3"=>null,
            "position"=>20
        ];


        Db::table('qualification_results')->insert($qualificationResults);
    }
}
