<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Driver;


class race_results07Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $raceResults=[];

        $raceResults[]=[
            "id"=>701,
            "driver_id"=>1,
            "race_id"=>7,
            "total_time"=>"01:48:51.980",
            "best_lap"=>85.201,
            "position"=>1,
            "points"=>25,
        ];
        $raceResults[]=[
            "id"=>702,
            "driver_id"=>14,
            "race_id"=>7,
            "total_time"=>"01:49:19.901",
            "best_lap"=>85.668,
            "position"=>2,
            "points"=>18,
        ];
        $raceResults[]=[
            "id"=>703,
            "driver_id"=>31,
            "race_id"=>7,
            "total_time"=>"01:49:19.901",
            "best_lap"=>84.231,
            "position"=>3,
            "points"=>15,
        ];
        $raceResults[]=[
            "id"=>704,
            "driver_id"=>44,
            "race_id"=>7,
            "total_time"=>"01:49:19.901",
            "best_lap"=>85.105,
            "position"=>4,
            "points"=>12,
        ];
        $raceResults[]=[
            "id"=>705,
            "driver_id"=>63,
            "race_id"=>7,
            "total_time"=>"01:49:19.901",
            "best_lap"=>87.209,
            "position"=>5,
            "points"=>10,
        ];
        $raceResults[]=[
            "id"=>706,
            "driver_id"=>16,
            "race_id"=>7,
            "total_time"=>"01:49:19.901",
            "best_lap"=>86.939,
            "position"=>6,
            "points"=>8,
        ];
        $raceResults[]=[
            "id"=>707,
            "driver_id"=>10,
            "race_id"=>7,
            "total_time"=>"01:49:19.901",
            "best_lap"=>86.578,
            "position"=>7,
            "points"=>6
        ];
        $raceResults[]=[
            "id"=>708,
            "driver_id"=>55,
            "race_id"=>7,
            "total_time"=>"01:49:19.901",
            "best_lap"=>86.283,
            "position"=>8,
            "points"=>4
        ];
        $raceResults[]=[
            "id"=>709,
            "driver_id"=>4,
            "race_id"=>7,
            "total_time"=>"00:00:00.01",
            "best_lap"=>86.888,
            "position"=>9,
            "points"=>2
        ];
        $raceResults[]=[
            "id"=>710,
            "driver_id"=>81,
            "race_id"=>7,
            "total_time"=>"00:00:00.01",
            "best_lap"=>84.785,
            "position"=>10,
            "points"=>1
        ];
        $raceResults[]=[
            "id"=>711,
            "driver_id"=>77,
            "race_id"=>7,
            "total_time"=>"00:00:00.01",
            "best_lap"=>84.139,
            "position"=>11,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>712,
            "driver_id"=>21,
            "race_id"=>7,
            "total_time"=>"00:00:00.01",
            "best_lap"=>88.038,
            "position"=>12,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>713,
            "driver_id"=>24,
            "race_id"=>7,
            "total_time"=>"00:00:00.01",
            "best_lap"=>86.615,
            "position"=>13,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>714,
            "driver_id"=>23,
            "race_id"=>7,
            "total_time"=>"00:00:00.01",
            "best_lap"=>87.816,
            "position"=>14,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>715,
            "driver_id"=>22,
            "race_id"=>7,
            "total_time"=>"00:00:00.02",
            "best_lap"=>94.205,
            "position"=>15,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>716,
            "driver_id"=>11,
            "race_id"=>7,
            "total_time"=>"00:00:00.02",
            "best_lap"=>90.273,
            "position"=>16,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>717,
            "driver_id"=>27,
            "race_id"=>7,
            "total_time"=>"00:00:00.02",
            "best_lap"=>90.260,
            "position"=>17,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>718,
            "driver_id"=>2,
            "race_id"=>7,
            "total_time"=>"00:00:00.02",
            "best_lap"=>89.076,
            "position"=>18,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>719,
            "driver_id"=>20,
            "race_id"=>7,
            "total_time"=>null,
            "best_lap"=>92.006,
            "position"=>19,
            "points"=>null
        ];
        $raceResults[]=[
            "id"=>720,
            "driver_id"=>18,
            "race_id"=>7,
            "total_time"=> null,
            "best_lap"=>92.384,
            "position"=>20,
            "points"=>null
        ];





        Db::table('race_results')->insert($raceResults);
    }
}
