<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Driver;


class race_results11Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $raceResults=[];

        $raceResults[]=[
            "id"=>1101,
            "driver_id"=>1,
            "race_id"=>11,
            "total_time"=>"01:25:33.607",
            "best_lap"=>67.012,
            "position"=>1,
            "points"=>25,
        ];
        $raceResults[]=[
            "id"=>1102,
            "driver_id"=>16,
            "race_id"=>11,
            "total_time"=>"01:25:38.762",
            "best_lap"=>69.990,
            "position"=>2,
            "points"=>18,
        ];
        $raceResults[]=[
            "id"=>1103,
            "driver_id"=>11,
            "race_id"=>11,
            "total_time"=>"01:25:50.795",
            "best_lap"=>69.317,
            "position"=>3,
            "points"=>15,
        ];
        $raceResults[]=[
            "id"=>1104,
            "driver_id"=>4,
            "race_id"=>11,
            "total_time"=>"01:25:59.934",
            "best_lap"=>69.877,
            "position"=>4,
            "points"=>10,
        ];
        $raceResults[]=[
            "id"=>1105,
            "driver_id"=>14,
            "race_id"=>11,
            "total_time"=>"01:26:03.924",
            "best_lap"=>69.512,
            "position"=>5,
            "points"=>8,
        ];
        $raceResults[]=[
            "id"=>1106,
            "driver_id"=>55,
            "race_id"=>11,
            "total_time"=>"01:26:04.984",
            "best_lap"=>69.348,
            "position"=>6,
            "points"=>12,
        ];
        $raceResults[]=[
            "id"=>1107,
            "driver_id"=>63,
            "race_id"=>11,
            "total_time"=>"01:26:23.010 ",
            "best_lap"=>70.160,
            "position"=>7,
            "points"=>4
        ];
        $raceResults[]=[
            "id"=>1108,
            "driver_id"=>44,
            "race_id"=>11,
            "total_time"=>"01:26:23.803",
            "best_lap"=>70.457,
            "position"=>8,
            "points"=>6
        ];
        $raceResults[]=[
            "id"=>1109,
            "driver_id"=>18,
            "race_id"=>11,
            "total_time"=>"01:26:34.650",
            "best_lap"=>69.340,
            "position"=>9,
            "points"=>1
        ];
        $raceResults[]=[
            "id"=>1110,
            "driver_id"=>10,
            "race_id"=>11,
            "total_time"=>"01:26:42.274",
            "best_lap"=>70.344,
            "position"=>10,
            "points"=>2
        ];
        $raceResults[]=[
            "id"=>1111,
            "driver_id"=>23,
            "race_id"=>11,
            "total_time"=>"01:26:54.374",
            "best_lap"=>70.604,
            "position"=>11,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>1112,
            "driver_id"=>24,
            "race_id"=>11,
            "total_time"=>"00:00:00.01",
            "best_lap"=>70.753,
            "position"=>12,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>1113,
            "driver_id"=>2,
            "race_id"=>11,
            "total_time"=>"00:00:00.01",
            "best_lap"=>70.501,
            "position"=>13,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>1114,
            "driver_id"=>31,
            "race_id"=>11,
            "total_time"=>"00:00:00.01",
            "best_lap"=>70.043,
            "position"=>14,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>1115,
            "driver_id"=>77,
            "race_id"=>11,
            "total_time"=>"00:00:00.01",
            "best_lap"=>70.092,
            "position"=>15,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>1116,
            "driver_id"=>81,
            "race_id"=>11,
            "total_time"=>"00:00:00.01",
            "best_lap"=>70.006,
            "position"=>16,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>1117,
            "driver_id"=>24,
            "race_id"=>11,
            "total_time"=>"00:00:00.01",
            "best_lap"=>70.697,
            "position"=>17,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>1118,
            "driver_id"=>20,
            "race_id"=>11,
            "total_time"=>"00:00:00.01",
            "best_lap"=>71.516,
            "position"=>18,
            "points"=>null
        ];
        $raceResults[]=[
            "id"=>1119,
            "driver_id"=>22,
            "race_id"=>11,
            "total_time"=>"00:00:00.01",
            "best_lap"=>70.372,
            "position"=>19,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>1120,
            "driver_id"=>27,
            "race_id"=>11,
            "total_time"=>null,
            "best_lap"=>null,
            "position"=>20,
            "points"=>null
        ];





        Db::table('race_results')->insert($raceResults);
    }
}
