<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Driver;


class race_results05Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $raceResults=[];

        $raceResults[]=[
            "id"=>501,
            "driver_id"=>1,
            "race_id"=>5,
            "total_time"=>"01:27:38.241",
            "best_lap"=>89.708,
            "position"=>1,
            "points"=>25,
        ];
        $raceResults[]=[
            "id"=>502,
            "driver_id"=>11,
            "race_id"=>5,
            "total_time"=>"01:27:43.625",
            "best_lap"=>90.560,
            "position"=>2,
            "points"=>18,
        ];
        $raceResults[]=[
            "id"=>503,
            "driver_id"=>14,
            "race_id"=>5,
            "total_time"=>"01:28:04.546",
            "best_lap"=>90.519,
            "position"=>3,
            "points"=>15,
        ];
        $raceResults[]=[
            "id"=>504,
            "driver_id"=>63,
            "race_id"=>5,
            "total_time"=>"01:28:11.470",
            "best_lap"=>91.015,
            "position"=>4,
            "points"=>12,
        ];
        $raceResults[]=[
            "id"=>505,
            "driver_id"=>55,
            "race_id"=>5,
            "total_time"=>"01:28:20.752",
            "best_lap"=>91.362,
            "position"=>5,
            "points"=>10,
        ];
        $raceResults[]=[
            "id"=>506,
            "driver_id"=>44,
            "race_id"=>5,
            "total_time"=>"01:28:29.490",
            "best_lap"=>90.669,
            "position"=>6,
            "points"=>8,
        ];
        $raceResults[]=[
            "id"=>507,
            "driver_id"=>16,
            "race_id"=>5,
            "total_time"=>"01:28:31.229",
            "best_lap"=>91.434,
            "position"=>7,
            "points"=>6
        ];
        $raceResults[]=[
            "id"=>508,
            "driver_id"=>10,
            "race_id"=>5,
            "total_time"=>"01:28:33.911",
            "best_lap"=>91.971,
            "position"=>8,
            "points"=>4
        ];
        $raceResults[]=[
            "id"=>509,
            "driver_id"=>31,
            "race_id"=>5,
            "total_time"=>"01:28:36.364",
            "best_lap"=>91.143,
            "position"=>9,
            "points"=>2
        ];
        $raceResults[]=[
            "id"=>510,
            "driver_id"=>20,
            "race_id"=>5,
            "total_time"=>"01:28:41.186",
            "best_lap"=>91.691,
            "position"=>10,
            "points"=>1
        ];
        $raceResults[]=[
            "id"=>511,
            "driver_id"=>22,
            "race_id"=>5,
            "total_time"=>"01:28:42.550",
            "best_lap"=>91.038,
            "position"=>11,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>512,
            "driver_id"=>18,
            "race_id"=>5,
            "total_time"=>"01:28:42.995",
            "best_lap"=>90.862,
            "position"=>12,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>513,
            "driver_id"=>77,
            "race_id"=>5,
            "total_time"=>"01:28:49.878",
            "best_lap"=>91.838,
            "position"=>13,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>514,
            "driver_id"=>23,
            "race_id"=>5,
            "total_time"=>"01:28:51.102",
            "best_lap"=>91.852,
            "position"=>14,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>515,
            "driver_id"=>27,
            "race_id"=>5,
            "total_time"=>"01:28:53.191",
            "best_lap"=>90.901,
            "position"=>15,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>516,
            "driver_id"=>24,
            "race_id"=>5,
            "total_time"=>"01:28:56.681",
            "best_lap"=>91.736,
            "position"=>16,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>517,
            "driver_id"=>4,
            "race_id"=>5,
            "total_time"=>"01:29:05.958",
            "best_lap"=>92.401,
            "position"=>17,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>518,
            "driver_id"=>21,
            "race_id"=>5,
            "total_time"=>"01:29:07.190",
            "best_lap"=>91.562,
            "position"=>18,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>519,
            "driver_id"=>81,
            "race_id"=>5,
            "total_time"=>"00:00:01.000",
            "best_lap"=>92.006,
            "position"=>19,
            "points"=>null
        ];
        $raceResults[]=[
            "id"=>520,
            "driver_id"=>2,
            "race_id"=>5,
            "total_time"=>"00:00:01.000",
            "best_lap"=>92.384,
            "position"=>20,
            "points"=>null
        ];





        Db::table('race_results')->insert($raceResults);
    }
}
