<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class SprintShootoutResult06Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         $sprintShootoutResults=[];
        $sprintShootoutResults[]=[
            "id"=>2101,
            "driver_id"=>4,
            'sprint_shootout_id'=>21,
            "q1"=>71.824,
            "q2"=>71.221,
            "q3"=>70.622,
            "position"=>1
        ];
        $sprintShootoutResults[]=[
            "id"=>2102,
            "driver_id"=>1,
            'sprint_shootout_id'=>21,
            "q1"=>71.888,
            "q2"=>71.262,
            "q3"=>70.683,
            "position"=>2
        ];
        $sprintShootoutResults[]=[
            "id"=>2103,
            "driver_id"=>11,
            'sprint_shootout_id'=>21,
            "q1"=>72.218,
            "q2"=>71.230,
            "q3"=>70.756,
            "position"=>3
        ];
        $sprintShootoutResults[]=[
            "id"=>2104,
            "driver_id"=>63,
            'sprint_shootout_id'=>21,
            "q1"=>71.976,
            "q2"=>71.516,
            "q3"=>70.857,
            "position"=>4
        ];
        $sprintShootoutResults[]=[
            "id"=>2105,
            "driver_id"=>44,
            'sprint_shootout_id'=>21,
            "q1"=>71.870,
            "q2"=>71.476,
            "q3"=>70.940,
            "position"=>5
        ];
        $sprintShootoutResults[]=[
            "id"=>2106,
            "driver_id"=>22,
            'sprint_shootout_id'=>21,
            "q1"=>72.358,
            "q2"=>71.676,
            "q3"=>71.019,
            "position"=>6
        ];
        $sprintShootoutResults[]=[
            "id"=>2107,
            "driver_id"=>16,
            'sprint_shootout_id'=>21,
            "q1"=> 72.107,
            "q2"=>71.473,
            "q3"=>71.077,
            "position"=>7
        ];
        $sprintShootoutResults[]=[
            "id"=>2108,
            "driver_id"=>3,
            'sprint_shootout_id'=>21,
            "q1"=>72.175,
            "q2"=>71.423,
            "q3"=>71.122,
            "position"=>8
        ];
        $sprintShootoutResults[]=[
            "id"=>2109,
            "driver_id"=>55,
            'sprint_shootout_id'=>21,
            "q1"=>71.796,
            "q2"=>71.491,
            "q3"=>71.126,
            "position"=>9
        ];
        $sprintShootoutResults[]=[
            "id"=>2110,
            "driver_id"=>81,
            'sprint_shootout_id'=>21,
            "q1"=>72.058,
            "q2"=>71.648,
            "q3"=>71.189,
            "position"=>10
        ];
        $sprintShootoutResults[]=[
            "id"=>2111,
            "driver_id"=>20,
            'sprint_shootout_id'=>21,
            "q1"=>72.058,
            "q2"=>71.727,
            "q3"=>null,
            "position"=>11
        ];
        $sprintShootoutResults[]=[
            "id"=>2112,
            "driver_id"=>27,
            'sprint_shootout_id'=>21,
            "q1"=>72.136,
            "q2"=>71.752,
            "q3"=>null,
            "position"=>12
        ];
        $sprintShootoutResults[]=[
            "id"=>2113,
            "driver_id"=>10,
            'sprint_shootout_id'=>21,
            "q1"=>72.229,
            "q2"=>71.822,
            "q3"=>null,
            "position"=>13
        ];
        $sprintShootoutResults[]=[
            "id"=>2114,
            "driver_id"=>77,
            'sprint_shootout_id'=>21,
            "q1"=>72.303,
            "q2"=>71.872,
            "q3"=>null,
            "position"=>14
        ];
        $sprintShootoutResults[]=[
            "id"=>2115,
            "driver_id"=>14,
            'sprint_shootout_id'=>21,
            "q1"=>72.224,
            "q2"=>null,
            "q3"=>null,
            "position"=>15
        ];
        $sprintShootoutResults[]=[
            "id"=>2116,
            "driver_id"=>31,
            'sprint_shootout_id'=>21,
            "q1"=>72.388,
            "q2"=>null,
            "q3"=>null,
            "position"=>16
        ];
        $sprintShootoutResults[]=[
            "id"=>2117,
            "driver_id"=>18,
            'sprint_shootout_id'=>21,
            "q1"=>72.482,
            "q2"=>null,
            "q3"=>null,
            "position"=>17
        ];
        $sprintShootoutResults[]=[
            "id"=>2118,
            "driver_id"=>24,
            'sprint_shootout_id'=>21,
            "q1"=>72.497,
            "q2"=>null,
            "q3"=>null,
            "position"=>18
        ];
        $sprintShootoutResults[]=[
            "id"=>2119,
            "driver_id"=>23,
            'sprint_shootout_id'=>21,
            "q1"=>72.525,
            "q2"=>null,
            "q3"=>null,
            "position"=>19
        ];
        $sprintShootoutResults[]=[
            "id"=>2120,
            "driver_id"=>2,
            'sprint_shootout_id'=>21,
            "q1"=>72.615,
            "q2"=>null,
            "q3"=>null,
            "position"=>20
        ];
        Db::table('sprint_shootout_results')->insert($sprintShootoutResults);
    }
}
