<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class DriversSeeder extends Seeder
{   
    
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $drivers=[];
        
        $drivers[]=[
            "id"=>16,
            "teams_id"=>1,
            "FirstName"=>"Charles",
            "LastName"=>"Leclerc",
            "country_id"=>7,
            "Number"=>16
        ];
        $drivers[]=[
            "id"=>55,
            "teams_id"=>1,
            "FirstName"=>"Carlos",
            "LastName"=>"Sainz",
            "country_id"=>8,
            "Number"=>55
        ];
        $drivers[]=[
            "id"=>1,
            "teams_id"=>2,
            "FirstName"=>"Max",
            "LastName"=>"Verstapen",
            "country_id"=>14,
            "Number"=>1
        ];
        $drivers[]=[
            "id"=>11,
            "teams_id"=>2,
            "FirstName"=>"Sergio",
            "LastName"=>"Perez",
            "country_id"=>18,
            "Number"=>11
        ];
        $drivers[]=[
            "id"=>14,
            "teams_id"=>3,
            "FirstName"=>"Fernando",
            "LastName"=>"Alonso",
            "country_id"=>8,
            "Number"=>14
        ];
        $drivers[]=[
            "id"=>18,
            "teams_id"=>3,
            "FirstName"=>"Lance",
            "LastName"=>"Stroll",
            "country_id"=>9,
            "Number"=>18
        ];
        $drivers[]=[
            "id"=>44,
            "teams_id"=>4,
            "FirstName"=>"Lewis",
            "LastName"=>"Hamilton",
            "country_id"=>11,
            "Number"=>44
        ];
        $drivers[]=[
            "id"=>63,
            "teams_id"=>4,
            "FirstName"=>"George",
            "LastName"=>"Russel",
            "country_id"=>11,
            "Number"=>63
        ];
        $drivers[]=[
            "id"=>77,
            "teams_id"=>5,
            "FirstName"=>"Valtteri",
            "LastName"=>"Bottas",
            "country_id"=>21,
            "Number"=>77
        ];
        $drivers[]=[
            "id"=>24,
            "teams_id"=>5,
            "FirstName"=>"Zhou",
            "LastName"=>"Guanyu",
            "country_id"=>26,
            "Number"=>24
        ];
        $drivers[]=[
            "id"=>10,
            "teams_id"=>6,
            "FirstName"=>"Pierre",
            "LastName"=>"Gasly",
            "country_id"=>22,
            "Number"=>10
        ];
        $drivers[]=[
            "id"=>31,
            "teams_id"=>6,
            "FirstName"=>"Esteban",
            "LastName"=>"Ocon",
            "country_id"=>22,
            "Number"=>31
        ];
        $drivers[]=[
            "id"=>23,
            "teams_id"=>7,
            "FirstName"=>"Alexander",
            "LastName"=>"Albon",
            "country_id"=>24,
            "Number"=>23
        ];
        $drivers[]=[
            "id"=>2,
            "teams_id"=>7,
            "FirstName"=>"Logan",
            "LastName"=>"Sargeant",
            "country_id"=>5,
            "Number"=>2
        ];
        $drivers[]=[
            "id"=>22,
            "teams_id"=>8,
            "FirstName"=>"Yuki",
            "LastName"=>"Tsunoda",
            "country_id"=>16,
            "Number"=>22
        ];
        $drivers[]=[
            "id"=>21,
            "teams_id"=>8,
            "FirstName"=>"Nyck",
            "LastName"=>"De Vries",
            "country_id"=>14,
            "Number"=>21
        ];
        $drivers[]=[
            "id"=>27,
            "teams_id"=>9,
            "FirstName"=>"Nico",
            "LastName"=>"Hulkenberg",
            "country_id"=>25,
            "Number"=>27
        ];
        $drivers[]=[
            "id"=>20,
            "teams_id"=>9,
            "FirstName"=>"Kevin",
            "LastName"=>"Magnussen",
            "country_id"=>23,
            "Number"=>20
        ];
        $drivers[]=[
            "id"=>4,
            "teams_id"=>10,
            "FirstName"=>"Lando",
            "LastName"=>"Norris",
            "country_id"=>11,
            "Number"=>4
        ];
        $drivers[]=[
            "id"=>81,
            "teams_id"=>10,
            "FirstName"=>"Oscar",
            "LastName"=>"Piastry",
            "country_id"=>3,
            "Number"=>81
        ];
        

        Db::table("drivers")->delete();
        Db::table("drivers")->insert($drivers);

    }
}
