<?php

namespace Database\Seeders\Seeders2024\RacesSeeders2024;


use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class race_results202401Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $raceResults=[];

        $raceResults[]=[
            "id"=>20240101,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"", //"01:33:56.736"
            "best_lap"=>null, // 096.236
            "position"=>1,
            "points"=>25,
        ];
        $raceResults[]=[
            "id"=>20240102,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"",
            "best_lap"=>null,
            "position"=>2,
            "points"=>18,
        ];
        $raceResults[]=[
            "id"=>20240103,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"",
            "best_lap"=>null,
            "position"=>3,
            "points"=>15,
        ];
        $raceResults[]=[
            "id"=>20240104,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"",
            "best_lap"=>null,
            "position"=>4,
            "points"=>12,
        ];
        $raceResults[]=[
            "id"=>20240105,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"",
            "best_lap"=>null,
            "position"=>5,
            "points"=>10,
        ];
        $raceResults[]=[
            "id"=>20240106,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"",
            "best_lap"=>null,
            "position"=>6,
            "points"=>8,
        ];
        $raceResults[]=[
            "id"=>20240107,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"", 
            "best_lap"=>null,
            "position"=>7,
            "points"=>6
        ];
        $raceResults[]=[
            "id"=>20240108,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"", 
            "best_lap"=>null,
            "position"=>8,
            "points"=>4
        ];
        $raceResults[]=[
            "id"=>20240109,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"", 
            "best_lap"=>null,
            "position"=>9,
            "points"=>2
        ];
        $raceResults[]=[
            "id"=>20240110,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"", 
            "best_lap"=>null,
            "position"=>10,
            "points"=>1
        ];
        $raceResults[]=[
            "id"=>20240111,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"", 
            "best_lap"=>null,
            "position"=>11,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>20240112,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"", 
            "best_lap"=>null,
            "position"=>12,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>20240113,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"", 
            "best_lap"=>null,
            "position"=>13,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>20240114,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"", 
            "best_lap"=>null,
            "position"=>14,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>20240115,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"", 
            "best_lap"=>null,
            "position"=>15,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>20240116,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"", 
            "best_lap"=>null,
            "position"=>16,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>20240117,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>"", 
            "best_lap"=>null,
            "position"=>17,
            "points"=>0
        ];
        $raceResults[]=[
            "id"=>20240118,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>null, 
            "best_lap"=>null,
            "position"=>18,
            "points"=>null
        ];
        $raceResults[]=[
            "id"=>20240119,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>null, 
            "best_lap"=>null,
            "position"=>19,
            "points"=>null
        ];
        $raceResults[]=[
            "id"=>20240120,
            "driver_id"=>0,
            "race_id"=>202401,
            "total_time"=>null, 
            "best_lap"=>null,
            "position"=>20,
            "points"=>null
        ];
        
        Db::table('race_results')->insert($raceResults);
    }
}
