<?php

namespace Database\Seeders\Seeders2024\QualificationsSeeders2024;


use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class qualification_results202401Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $qualificationResults=[];
        
        $qualificationResults[]=[
            "id"=>20240101,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0, //91.295
            "q2"=>0,
            "q3"=>0,
            "position"=>1
        ];
        $qualificationResults[]=[
            "id"=>20240102,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>2
        ];
        $qualificationResults[]=[
            "id"=>20240103,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>3
        ];
        $qualificationResults[]=[
            "id"=>20240104,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>4
        ];
        $qualificationResults[]=[
            "id"=>20240105,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>5
        ];
        $qualificationResults[]=[
            "id"=>20240106,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>6
        ];
        $qualificationResults[]=[
            "id"=>20240107,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>7
        ];
        $qualificationResults[]=[
            "id"=>20240108,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>8
        ];
        $qualificationResults[]=[
            "id"=>20240109,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>9
        ];
        $qualificationResults[]=[
            "id"=>20240110,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>null,
            "position"=>10
        ];
        $qualificationResults[]=[
            "id"=>20240111,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>null,
            "position"=>11
        ];
        $qualificationResults[]=[
            "id"=>20240112,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>null,
            "position"=>12
        ];
        $qualificationResults[]=[
            "id"=>20240113,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>null,
            "position"=>13
        ];
        $qualificationResults[]=[
            "id"=>20240114,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>null,
            "position"=>14
        ];
        $qualificationResults[]=[
            "id"=>20240115,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>0,
            "q3"=>null,
            "position"=>15
        ];
        $qualificationResults[]=[
            "id"=>20240116,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>null,            
            "q3"=>null,
            "position"=>16
        ];
        $qualificationResults[]=[
            "id"=>20240117,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>null,            
            "q3"=>null,
            "position"=>17
        ];
        $qualificationResults[]=[
            "id"=>20240118,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>null,            
            "q3"=>null,
            "position"=>18
        ];
        $qualificationResults[]=[
            "id"=>20240119,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>null,            
            "q3"=>null,
            "position"=>19
        ];
        $qualificationResults[]=[
            "id"=>20240120,
            "driver_id"=>0,
            'qualification_id'=>202401,
            "q1"=>0,
            "q2"=>null,            
            "q3"=>null,
            "position"=>20
        ];

        Db::table('qualification_results')->insert($qualificationResults);
    }
}
