<?php

namespace Database\Seeders\Seeders2024\SprintsShootoutsSeeders2024;


use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class SprintShootoutResult202405Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         $sprintShootoutResults=[];
        $sprintShootoutResults[]=[
            "id"=>20240501,
            "driver_id"=>16,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>1
        ];
        $sprintShootoutResults[]=[
            "id"=>20240502,
            "driver_id"=>11,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>2
        ];
        $sprintShootoutResults[]=[
            "id"=>20240503,
            "driver_id"=>1,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>3
        ];
        $sprintShootoutResults[]=[
            "id"=>20240504,
            "driver_id"=>63,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>4
        ];
        $sprintShootoutResults[]=[
            "id"=>20240505,
            "driver_id"=>55,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>5
        ];
        $sprintShootoutResults[]=[
            "id"=>20240506,
            "driver_id"=>44,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>6
        ];
        $sprintShootoutResults[]=[
            "id"=>20240507,
            "driver_id"=>23,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>7
        ];
        $sprintShootoutResults[]=[
            "id"=>20240508,
            "driver_id"=>14,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>8
        ];
        $sprintShootoutResults[]=[
            "id"=>20240509,
            "driver_id"=>18,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>0,
            "position"=>9
        ];
        $sprintShootoutResults[]=[
            "id"=>20240510,
            "driver_id"=>4,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>null,
            "position"=>10
        ];
        $sprintShootoutResults[]=[
            "id"=>20240511,
            "driver_id"=>81,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>null,
            "position"=>11
        ];
        $sprintShootoutResults[]=[
            "id"=>20240512,
            "driver_id"=>27,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>103.806,
            "q3"=>null,
            "position"=>12
        ];
        $sprintShootoutResults[]=[
            "id"=>20240513,
            "driver_id"=>31,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>null,
            "position"=>13
        ];
        $sprintShootoutResults[]=[
            "id"=>20240514,
            "driver_id"=>20,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>0,
            "q3"=>null,
            "position"=>14
        ];
        $sprintShootoutResults[]=[
            "id"=>20240515,
            "driver_id"=>2,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>null,
            "q3"=>null,
            "position"=>15
        ];
        $sprintShootoutResults[]=[
            "id"=>20240516,
            "driver_id"=>24,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>null,
            "q3"=>null,
            "position"=>16
        ];
        $sprintShootoutResults[]=[
            "id"=>20240517,
            "driver_id"=>77,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>null,
            "q3"=>null,
            "position"=>17
        ];
        $sprintShootoutResults[]=[
            "id"=>20240518,
            "driver_id"=>22,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>null,
            "q3"=>null,
            "position"=>18
        ];
        $sprintShootoutResults[]=[
            "id"=>20240519,
            "driver_id"=>10,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>null,
            "q3"=>null,
            "position"=>19
        ];
        $sprintShootoutResults[]=[
            "id"=>20240520,
            "driver_id"=>21,
            'sprint_shootout_id'=>202405,
            "q1"=>0,
            "q2"=>null,
            "q3"=>null,
            "position"=>20
        ];

        Db::table('sprint_shootout_results')->insert($sprintShootoutResults);
    }
}
